/*
>>>> Create html report.
        The current docker image of Jenkins has htmlextra installed.
        Open build steps.
        Add these command in the execute shell.
            newman --version
            newman run "https://api.postman.com/collections/{collection_id}?access_key=$POSTMAN_API_KEY" --reporters cli,htmlextra --reporter-htmlextra-export newman/report.html
>>>> To view the report.
        Go to the job -> workspace -> newman -> report.html
        The report.html file is not properly aligned in the jenkins.
        Click on the inspect and view the errors in the console tab.
        In Jenkins, there are many files generated by untrusted sources, those found in project workspaces.

        Jenkins distributes files like this one with a content security policy, CSP as an HTTP header. By default, the CSP header is configured to prohibit various web features in order to guard against cross-site scripting and other threats against users of Jenkins who access these files. That is why we cannot see this report properly.
>>>> To show reports properly.
        Go to Dashboard -> Manage Jenkins -> Script Console
        Paste the content from the txt file in the current folder into the text area.
        Click on Run.
        By running the script, we are changing some jenkins security settings.
>>>> Jenkins - Configuring Content Security Policy
        Reference Link: https://www.jenkins.io/doc/book/security/configuring-content-security-policy/
>>>> How to view the html report on the job page itself.
        Install the jenkins plugin
            Dashboard -> Manage Jenkins -> Manage Plugins -> Available Plugin
            Search HTML Publisher.
            Click on Install without restart option.

        Open Job.
        Configuration -> Post-build Actions.
        Add post-build action -> Select Publish HTML reports.
        Open additional options and set the below path in the Index page field.
            newman/report.html
        Add also a proper report title.

        Again build the job.
        Refresh the page.
        You can view the report on the job page itself.
*/