/*
 * Simple Request – Sends a GET request asynchronously and stores the UUID globally.
 * Note: pm.sendRequest runs asynchronously within Postman scripts.
 */
pm.sendRequest('https://httpbin.org/uuid', function (error, response) {
    const data = response.json();
    pm.globals.set('uuid', data.uuid);
});


/*
 * Advanced Request – Sends a GET request with custom headers
 * and stores the returned UUID in a Postman global variable.
 * Code can be autogenerated from an existing request in postman. (See the attached gif) 
 */
const options = {
    method: 'GET',
    url: 'https://httpbin.org/uuid',
    header: {
        'Cache-Control': 'no-cache',
        'Foo': 'Bar'
    }
};

pm.sendRequest(options, function (error, response) {
    const data = response.json();
    pm.globals.set('uuid', data.uuid);
});